"""empty message

Revision ID: 21eefe29af90
Revises: 6da378a8fdc9
Create Date: 2017-07-23 16:25:31.162418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21eefe29af90'
down_revision = '6da378a8fdc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decline_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('practice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('user_declined_practice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_declined_practice',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('practice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name='user_declined_practice_practice_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_declined_practice_user_id_fkey')
    )
    op.drop_table('decline_notice')
    # ### end Alembic commands ###
