"""empty message

Revision ID: 6da378a8fdc9
Revises: 
Create Date: 2017-07-23 13:09:10.070586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da378a8fdc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'club', ['id'])
    op.create_unique_constraint(None, 'practice', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'practice', type_='unique')
    op.drop_constraint(None, 'club', type_='unique')
    # ### end Alembic commands ###
